# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
#safe: true


# edit here to achieve your personal greatness
url: https://www.miguelnunezburguera.com
baseurl: /
title: Miguel Francisco Nuñez Bueguera
author: Miguel Francisco Nuñez Burguera
description: Personal blog and resume
avatar: profile.png
email: miguelfrancisco85@gmail.com
github:  miguelfrancisco85# username
twitter: Miguelfrancisco
linkedin: miguel-francisco-nunez-burguera
stackoverflow: /users/9019014/miguelfrancisco85   #e.g: users/2735833/proton1h1
#medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
#disqus: username
google_analytics: G-MX0VKRNCKH


# needed for travis-ci build
exclude: [vendor]